DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE "likes" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "owner_id" INTEGER REFERENCES users(id) NOT NULL,
  "resource_id" INTEGER REFERENCES resources(id) NOT NULL
);
