DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE "comments" (
  "id" SERIAL PRIMARY KEY NOT NULL,
  "commentor_id" INTEGER REFERENCES users(id) ON DELETE CASCADE,
  "resource_id" INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  "text" TEXT NOT NULL,
  "date_posted" TIMESTAMP NOT NULL DEFAULT NOW()
);
